version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      # Zookeeper bağlantısı
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Kafka'nın içeride hangi IP/port'tan dinleyeceği
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

      # Dışarıdan (host'tan) erişimde reklam edeceği adres
      # Docker host makinesinden "localhost:9092" ile erişmek istiyorsanız bu şekilde ayarlayabilirsiniz.
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      # Topic'lerin otomatik oluşturulmasını istiyorsanız:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # Partitions, consumer offset vb. dahili topiclerin replikasyon sayısı (tek broker ise 1 olmalı)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
